version: "3.3"

services:
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - ticket-net
  server:
    restart: always
    build: .
    volumes:
      - /app/node_modules
      - ./:/app
    ports:
      - "5000:5000"
    networks:
      - ticket-net
networks:
  ticket-net:
